apiVersion: apps/v1
kind: Deployment
metadata:
  name: notvulnerable-deployment
  labels:
    app: notvulnerable-deployment
spec:
  replicas: 0 # testing purposes only
  selector:
    matchLabels:
      app: notvulnerable-deployment
  template:
    metadata:
      labels:
        app: notvulnerable-deployment
    spec:
      containers:
      - name: static
        image: gcr.io/distroless/static:latest
