apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-deployment
  labels:
    app: vulnerable-deployment
spec:
  replicas: 0 # testing purposes only
  selector:
    matchLabels:
      app: vulnerable-deployment
  template:
    metadata:
      labels:
        app: vulnerable-deployment
    spec:
      containers:
      - name: alpine1
        image: alpine:3.10.0
      - name: alpine2
        image: alpine:3.11.0
