apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-deployment
  labels:
    app: vulnerable-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: vulnerable-deployment
  template:
    metadata:
      labels:
        app: vulnerable-deployment
    spec:
      containers:
      - name: kubectl
        image: mcr.microsoft.com/oss/kubernetes/kubectl:v1.20.8
      - name: nginx
        image: nginx:1.15.2
