apiVersion: v1
kind: Service
metadata:
  name: trivy-provider
  namespace: trivy-provider
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: trivy-provider
  sessionAffinity: None
